### ISSUE TITLE
Mining Air

### ISSUE THREAD

**Issue by EvenMoreEvenSteven** [UnhappyCodings/vanillaquarry#3]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The Quarry tries to mine air blocks. This means that "mining" air costs fuel and makes the process way longer, since it has to mine every air block on a layer before moving onto the next.

### Multiplayer?

Singleplayer

### Operating System?

Windows

### Version

1.1r

### Minecraft Version

1.19.2

### Forge Version

43.1.38

**Comment by UnhappyCodings** [comment]
Hey! I am already on implementing a "Skip Air" button to the gui. Feature will be uploaded soon to Curseforge!

**Comment by EvenMoreEvenSteven** [comment]
Oh cool! I'd ask for a release but I thonk thats considered rude, and could
cause stress. Thank you!

**Comment by UnhappyCodings** [comment]
I am currently not at home. Will keep working on it later today and probably upload it tomorrow or monday :)

**Comment by EvenMoreEvenSteven** [comment]
Thank you very much!

**Comment by UnhappyCodings** [comment]
Hey!

the above reported features has been implemented and is uploaded to Curseforge! (1.6r)
If you have any other questions related to this post, feel free to post them.
Otherwise you can close the issue now.

If you have any other question feel free to join our discord server: https://discord.intelligence-modding.de/
Thank you for the using Quarry and have a nice day! \:)
